# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
all:
  vars:
    users:
      # @todo this is where you define which development team members have access to the server.
      # If you need to remove access from someone, do not remove them from this list, but instead set their state: absent
      - name: minhaj
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIqrgegBAJdWBsYS9k+7KyJISl9gXjYEdXqmef/FrGwLalcwZ18/LmvjD8s/qE6Aw7atWnjhamUISYNjSbgUTdR7w1k1Pc8b3+bkRMsYCpB23jK3NPuq6diQ/ieGyvNLL/umNtdCZffx47lpgIetSK2TvhgjHNKQGy0C1qUjxEIsHrSx5Xlsh8v12BvpkBeF3+wVESc5CodtD6oCaj/N2kHjgLvjjURK202FLF4NIjByG7ZYmr4/zZiTiKiTsA4On8BiWJTTxCBG1kTSEC3BmTIi139O/Z9zq/Ub61RAxCLU/SOS+SFAjFwBuK5/2q7mETZxFqGlcwRJcuiV8bMsmPSi+cr4fTLWMYd7R4q5pf9ZSwRpSRJPIF47VO+Tf2/DEHFJewPgL15pcD7Fpu7KZVKmM80A8u/UiPmiwvMevIbVvqpoPFDzIgeD9rOWk1feAMz7NQLaHJROsBF0NcQOzUIBGR3hm1izGgYQ2zq/O7+FgPwV9/OehwWjZypvv/6V8= minhaj@TECHNO-500
        state: present
        sudoer: true

docker-manager-first:
  hosts:
    ip-172-31-42-204: # @todo set this to be the hostname of your target server
      ansible_host: '13.126.130.150' # @todo set this to be the IP address of your server
      data_label: data1 # for manager machines, this should always be "data1"

# QA and staging servers are not configured to use workers.
docker-workers: {}
